### ISSUE TITLE
[BUG] - DokuWiki XMLRPC Login to IIS set for AD authentication fails

### ISSUE THREAD

**Issue by darusdp** [AndyDLP/PSDokuWiki#10]
Not necessarily a bug, but I was hoping someone could help.

Dokuwiki-Connect doesn't work with DokuWiki AD Authentication

I see that Dokuwiki-Connect gets turned into:

$httpResponse = Invoke-WebRequest -Uri 'http://gruwikipre01/lib/exe/xmlrpc.php' -Method Post -Headers @{ "Content-Type" = "text/xml"; } -Body "<?xml version=`"1.0`"?><methodCall><methodName>dokuwiki.login</methodName><params><param><value><string>username</string></value></param><param><value><string>password</string></value></param></params></methodCall>" -SessionVariable WebSession -ErrorAction Stop

If IIS is set to use Anonymous Authentication it works. However, that cause us other issues in that we use AD Authnetication for Dokuwiki for SSO (can't lose that functionality).

If IIS doesn't have Anonymous Authentication and only Windows Authentication then login doesn't work - return 401.2 error.

I don't know how to code an Invoke-WebRequest that will work to establish a dokuwiki connection so that other commands can be issued. Even if I knew I'm not sure it will work on the IIS server with only Windows Authentication enabled and Anonymous Authentication disabled.

Thanks, Dave

**Comment by darusdp** [comment]
The issue is because IIS can't have both Anonymous and Windows Authentication on the same website at the same time.

The solution is to make a virtual directory/application for XML-RPC to point to and set authentication mode to Anonymous.

Then using PSDokuWiki I ran into and issue with the Internet Explorer engine not available or never had first time settings done or use -UseBasicParing in the Invoke-WebRequest call.

Searching Internet for fix to IE engine had two solutions. 1. -UseBasicParsing 2. Make Group Policy to deal with IE initial settings.

Solution #2 didn't work for me though others got it to.
http://wahlnetwork.com/2015/11/17/solving-the-first-launch

I updated the PSDokuWiki scripts to have -UserBasicParsing when it calls Invoke-WebRequest. Only found 2 places (so far) where it is needed. In Connect-DokuServer.ps1 and the Invoke-DokuWikiApiCall.ps1

All is working now with these changes. 

A better solution would be to add a parameter to PSDokuWiki cmdlets to allow for basic parsing or not and the script code changed to execute based on param passed. I may do that later.

**Comment by AndyDLP** [comment]
Hi Dave,

Sorry for the delayed response with this. I will reopen this ticket for now so if you do decide to add a param to change it to basic parsing, you can make a pull request with the change and I will merge it in.
Would you also mind sharing the specific steps you did with the virtual host so I can add it to the readme? I'm sure it's probably a much more common scenario having a Windows web server when using the powershell module! 

I'm currently running the wiki on centos / nginx so haven't tested with IIS, I should probably try and add that to the AppVeyor process somehow... food for thought!

Cheers,
Andy

**Comment by darusdp** [comment]
Andy, I will get to this soon. May be next week.

**Comment by darusdp** [comment]
Andy, it turns out that Anonymous Authentication is not necessary. I was running Powershell under a different account then I used with Dokuwiki-Connect. I thought it would use the credentials from Dokuwiki-Connect but it was using my Powershell account. Once I ran Powershell under the same account and it used with Dokuwiki-Connect all was fine with Windows Authentication setup.

I've actually never done a pull request and updated code in GitHub but I will figure it out.

**Comment by darusdp** [comment]
Andy, I've submitted the updated code. Sorry if I did it wrong. GitHub desktop wouldn't publish the branch due to permission failure. Yet, I was able to edit code via Browser on GitHub site. That made a pull request per file. That's why there are 12 and not just 1.

**Comment by AndyDLP** [comment]
No worries Dave. It turns out that the functionality you added to 10 of the functions was already in place via the ([common parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-6)).

As for the other part with the UseBasicParsing, I've elaborated a bit more at:
https://github.com/AndyDLP/PSDokuWiki/pull/12

Cheers!

Andy
