### ISSUE TITLE
[FEATURE] - Command for other API calls.

### ISSUE THREAD

**Issue by jorgemarti** [AndyDLP/PSDokuWiki#32]
Some API calls are not covered by the commands provided by this module, for instance those which are extensions of the XML API provided by plugins:

https://www.dokuwiki.org/plugin:struct:remote_api

It would be nice if there was a way of wrapping those API methods as well, including a generic command which would take also parameters.

**Comment by AndyDLP** [comment]
Hmm, good point... I've not personally used the API with any other plugins but I think if we just move `Invoke-DokuApiCall` from Private and into Public, then that will do the job.

I'll try and have a look this weekend, if you fancy testing it manually and doing a PR you are more than welcome of course 😄

**Comment by jorgemarti** [comment]
Thanks. I'm afraid I'm not that fluent in Powershell as I would like 😓
